import { Project, Task, Note, ActivityLog } from './types'

export const MOCK_TASKS: Task[] = [
  { id: 't1', project_id: 'p1', title: 'Configurar repositório', done: true, position: 0, created_at: '2024-01-10T10:00:00Z' },
  { id: 't2', project_id: 'p1', title: 'Criar wireframes', done: true, position: 1, created_at: '2024-01-11T10:00:00Z' },
  { id: 't3', project_id: 'p1', title: 'Implementar autenticação', done: true, position: 2, created_at: '2024-01-12T10:00:00Z' },
  { id: 't4', project_id: 'p1', title: 'Build Kanban board', done: false, position: 3, created_at: '2024-01-13T10:00:00Z' },
  { id: 't5', project_id: 'p1', title: 'Integração com Supabase', done: false, position: 4, created_at: '2024-01-14T10:00:00Z' },
  { id: 't6', project_id: 'p1', title: 'Deploy na Vercel', done: false, position: 5, created_at: '2024-01-15T10:00:00Z' },

  { id: 't7', project_id: 'p2', title: 'Pesquisa de mercado', done: true, position: 0, created_at: '2024-02-01T10:00:00Z' },
  { id: 't8', project_id: 'p2', title: 'Definir stack tecnológico', done: true, position: 1, created_at: '2024-02-02T10:00:00Z' },
  { id: 't9', project_id: 'p2', title: 'Criar MVP', done: false, position: 2, created_at: '2024-02-03T10:00:00Z' },

  { id: 't10', project_id: 'p3', title: 'Estudar módulo 1', done: true, position: 0, created_at: '2024-03-01T10:00:00Z' },
  { id: 't11', project_id: 'p3', title: 'Estudar módulo 2', done: true, position: 1, created_at: '2024-03-05T10:00:00Z' },
  { id: 't12', project_id: 'p3', title: 'Fazer exercícios práticos', done: false, position: 2, created_at: '2024-03-10T10:00:00Z' },
  { id: 't13', project_id: 'p3', title: 'Projeto final', done: false, position: 3, created_at: '2024-03-15T10:00:00Z' },

  { id: 't14', project_id: 'p4', title: 'Mapear processos manuais', done: true, position: 0, created_at: '2024-01-20T10:00:00Z' },
  { id: 't15', project_id: 'p4', title: 'Criar script de automação', done: true, position: 1, created_at: '2024-01-25T10:00:00Z' },
  { id: 't16', project_id: 'p4', title: 'Testes e validação', done: true, position: 2, created_at: '2024-02-01T10:00:00Z' },
  { id: 't17', project_id: 'p4', title: 'Documentar processo', done: true, position: 3, created_at: '2024-02-05T10:00:00Z' },

  { id: 't18', project_id: 'p5', title: 'Esboço inicial', done: true, position: 0, created_at: '2024-04-01T10:00:00Z' },
  { id: 't19', project_id: 'p5', title: 'Desenvolver funcionalidades core', done: false, position: 1, created_at: '2024-04-05T10:00:00Z' },
  { id: 't20', project_id: 'p5', title: 'Testes unitários', done: false, position: 2, created_at: '2024-04-10T10:00:00Z' },

  { id: 't21', project_id: 'p6', title: 'Ideia inicial documentada', done: true, position: 0, created_at: '2024-05-01T10:00:00Z' },
  { id: 't22', project_id: 'p6', title: 'Definir escopo', done: false, position: 1, created_at: '2024-05-05T10:00:00Z' },
]

export const MOCK_NOTES: Note[] = [
  { id: 'n1', project_id: 'p1', content: '## Progresso\n\nO projeto está avançando bem. Preciso focar no módulo de drag-and-drop esta semana.\n\n- Kanban funcionando parcialmente\n- Auth implementado', created_at: '2024-01-20T14:30:00Z' },
  { id: 'n2', project_id: 'p1', content: 'Lembrar de implementar RLS no Supabase antes do deploy.', created_at: '2024-01-22T09:15:00Z' },
  { id: 'n3', project_id: 'p2', content: '## Insights da pesquisa\n\nO mercado está aquecido para soluções B2B de automação. Focar no segmento de PMEs.', created_at: '2024-02-10T11:00:00Z' },
  { id: 'n4', project_id: 'p3', content: 'Excelente curso! Os módulos de TypeScript avançado são muito bons.', created_at: '2024-03-20T16:45:00Z' },
]

export const MOCK_ACTIVITY: ActivityLog[] = [
  { id: 'a1', project_id: 'p1', action: 'Status alterado de ideia para andamento', detail: null, created_at: '2024-01-15T10:00:00Z' },
  { id: 'a2', project_id: 'p1', action: 'Tarefa concluída', detail: 'Configurar repositório', created_at: '2024-01-16T11:30:00Z' },
  { id: 'a3', project_id: 'p1', action: 'Tarefa concluída', detail: 'Criar wireframes', created_at: '2024-01-18T14:20:00Z' },
  { id: 'a4', project_id: 'p1', action: 'Nova anotação adicionada', detail: null, created_at: '2024-01-20T14:30:00Z' },
  { id: 'a5', project_id: 'p1', action: 'Tarefa concluída', detail: 'Implementar autenticação', created_at: '2024-01-25T09:00:00Z' },
  { id: 'a6', project_id: 'p1', action: 'Edição salva', detail: 'Informações gerais atualizadas', created_at: '2024-02-01T10:00:00Z' },
  { id: 'a7', project_id: 'p2', action: 'Status alterado de ideia para planejamento', detail: null, created_at: '2024-02-01T09:00:00Z' },
  { id: 'a8', project_id: 'p2', action: 'Tarefa concluída', detail: 'Pesquisa de mercado', created_at: '2024-02-05T16:00:00Z' },
  { id: 'a9', project_id: 'p3', action: 'Status alterado de ideia para andamento', detail: null, created_at: '2024-03-01T08:00:00Z' },
  { id: 'a10', project_id: 'p3', action: 'Tarefa concluída', detail: 'Estudar módulo 1', created_at: '2024-03-08T17:00:00Z' },
  { id: 'a11', project_id: 'p4', action: 'Status alterado de andamento para concluido', detail: null, created_at: '2024-02-10T12:00:00Z' },
  { id: 'a12', project_id: 'p5', action: 'Status alterado de ideia para planejamento', detail: null, created_at: '2024-04-01T10:00:00Z' },
]

const now = new Date()
const daysFromNow = (days: number) => {
  const d = new Date(now)
  d.setDate(d.getDate() + days)
  return d.toISOString().split('T')[0]
}
const monthsAgo = (months: number) => {
  const d = new Date(now)
  d.setMonth(d.getMonth() - months)
  return d.toISOString()
}

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'p1',
    name: 'ProjectHub',
    description: 'Sistema pessoal de gestão de projetos com Kanban, dashboard de métricas e integrações.',
    status: 'andamento',
    category: 'pessoal',
    type: 'app',
    priority: 'alta',
    deadline: daysFromNow(5),
    github_url: 'https://github.com/vercel/next.js',
    notion_url: 'https://notion.so/projecthub',
    calendar_event_id: null,
    technologies: ['React', 'TypeScript', 'Supabase', 'Tailwind'],
    created_at: monthsAgo(3),
    updated_at: monthsAgo(0),
    user_id: 'user1',
    tasks: MOCK_TASKS.filter(t => t.project_id === 'p1'),
    notes: MOCK_NOTES.filter(n => n.project_id === 'p1'),
    activity_log: MOCK_ACTIVITY.filter(a => a.project_id === 'p1'),
  },
  {
    id: 'p2',
    name: 'SaaS de Automação B2B',
    description: 'Plataforma para automatizar workflows de PMEs com integração a ferramentas populares.',
    status: 'planejamento',
    category: 'empresa',
    type: 'automacao',
    priority: 'alta',
    deadline: daysFromNow(30),
    github_url: null,
    notion_url: 'https://notion.so/saas-automacao',
    calendar_event_id: null,
    technologies: ['Node.js', 'PostgreSQL', 'React', 'Docker'],
    created_at: monthsAgo(2),
    updated_at: monthsAgo(1),
    user_id: 'user1',
    tasks: MOCK_TASKS.filter(t => t.project_id === 'p2'),
    notes: MOCK_NOTES.filter(n => n.project_id === 'p2'),
    activity_log: MOCK_ACTIVITY.filter(a => a.project_id === 'p2'),
  },
  {
    id: 'p3',
    name: 'Curso TypeScript Avançado',
    description: 'Estudo aprofundado de TypeScript com foco em patterns avançados e performance.',
    status: 'andamento',
    category: 'pessoal',
    type: 'estudo',
    priority: 'media',
    deadline: daysFromNow(14),
    github_url: null,
    notion_url: null,
    calendar_event_id: null,
    technologies: ['TypeScript'],
    created_at: monthsAgo(2),
    updated_at: monthsAgo(0),
    user_id: 'user1',
    tasks: MOCK_TASKS.filter(t => t.project_id === 'p3'),
    notes: MOCK_NOTES.filter(n => n.project_id === 'p3'),
    activity_log: MOCK_ACTIVITY.filter(a => a.project_id === 'p3'),
  },
  {
    id: 'p4',
    name: 'Automação de Relatórios',
    description: 'Script Python para gerar relatórios mensais automaticamente e enviar por email.',
    status: 'concluido',
    category: 'empresa',
    type: 'automacao',
    priority: 'media',
    deadline: null,
    github_url: 'https://github.com/torvalds/linux',
    notion_url: null,
    calendar_event_id: null,
    technologies: ['Python', 'Pandas', 'SMTP'],
    created_at: monthsAgo(4),
    updated_at: monthsAgo(3),
    user_id: 'user1',
    tasks: MOCK_TASKS.filter(t => t.project_id === 'p4'),
    notes: [],
    activity_log: MOCK_ACTIVITY.filter(a => a.project_id === 'p4'),
  },
  {
    id: 'p5',
    name: 'App Mobile de Fitness',
    description: 'Aplicativo para tracking de treinos e nutrição com gamificação.',
    status: 'planejamento',
    category: 'pessoal',
    type: 'app',
    priority: 'baixa',
    deadline: daysFromNow(3),
    github_url: null,
    notion_url: null,
    calendar_event_id: null,
    technologies: ['React Native', 'Expo', 'Firebase'],
    created_at: monthsAgo(1),
    updated_at: monthsAgo(0),
    user_id: 'user1',
    tasks: MOCK_TASKS.filter(t => t.project_id === 'p5'),
    notes: [],
    activity_log: MOCK_ACTIVITY.filter(a => a.project_id === 'p5'),
  },
  {
    id: 'p6',
    name: 'Blog Técnico Pessoal',
    description: 'Blog estático com artigos sobre desenvolvimento, carreira e open source.',
    status: 'ideia',
    category: 'pessoal',
    type: 'outro',
    priority: 'baixa',
    deadline: null,
    github_url: null,
    notion_url: null,
    calendar_event_id: null,
    technologies: ['Next.js', 'MDX'],
    created_at: monthsAgo(1),
    updated_at: monthsAgo(1),
    user_id: 'user1',
    tasks: MOCK_TASKS.filter(t => t.project_id === 'p6'),
    notes: [],
    activity_log: MOCK_ACTIVITY.filter(a => a.project_id === 'p6'),
  },
  {
    id: 'p7',
    name: 'Pipeline CI/CD Corporativo',
    description: 'Padronização do pipeline de deploy para todos os microsserviços da empresa.',
    status: 'pausado',
    category: 'empresa',
    type: 'automacao',
    priority: 'alta',
    deadline: daysFromNow(-5),
    github_url: null,
    notion_url: null,
    calendar_event_id: null,
    technologies: ['GitHub Actions', 'Docker', 'Kubernetes'],
    created_at: monthsAgo(3),
    updated_at: monthsAgo(2),
    user_id: 'user1',
    tasks: [],
    notes: [],
    activity_log: [],
  },
]
